"""
Extended cross-domain probes for Paper 3 scale experiments.

150 probes total: 25 per domain pair (6 pairs).
Each probe requires genuine dual-domain expertise — not just mentioning
two fields, but requiring knowledge from both to complete the text coherently.

Format: list of (probe_text, (domain1, domain2)) tuples.
Designed for max_length=128 tokenization.
"""

EXTENDED_CROSS_DOMAIN_PROBES = [
    # ================================================================
    # medical + legal (25 probes)
    # ================================================================
    ("Medical malpractice claims require proving that the physician's treatment deviated from the accepted standard of care, which in cases involving off-label drug prescription means demonstrating that no reasonable physician would have prescribed",
     ('medical', 'legal')),
    ("The FDA regulatory pathway for emergency use authorization of vaccines differs from full approval in that clinical trial data requirements for safety and efficacy are",
     ('medical', 'legal')),
    ("Informed consent doctrine requires physicians to disclose material risks of a procedure, where materiality is determined by whether a reasonable patient would consider the information significant when deciding whether to undergo",
     ('medical', 'legal')),
    ("HIPAA privacy regulations govern the disclosure of protected health information by covered entities, with exceptions for public health surveillance requiring notification when a patient presents with",
     ('medical', 'legal')),
    ("Expert witness testimony in toxic tort litigation must establish both general causation showing the substance can cause the disease and specific causation showing the plaintiff's exposure to the",
     ('medical', 'legal')),
    # --- new probes below ---
    ("Wrongful death claims arising from surgical complications require the plaintiff's medical expert to reconstruct the intraoperative sequence and identify the specific deviation from standard laparoscopic technique that caused the",
     ('medical', 'legal')),
    ("The Americans with Disabilities Act requires employers to provide reasonable accommodations for employees with chronic conditions, which for workers diagnosed with multiple sclerosis may include modified schedules to account for fatigue patterns associated with",
     ('medical', 'legal')),
    ("Drug product liability lawsuits under strict liability theory must demonstrate a manufacturing defect or failure to warn, which for opioid analgesics means showing that the pharmaceutical company knew about the dose-dependent risk of respiratory depression and",
     ('medical', 'legal')),
    ("Workers' compensation claims for occupational lung disease require establishing that cumulative exposure to silica dust exceeded permissible exposure limits and that the resulting pulmonary fibrosis was confirmed by high-resolution computed tomography showing",
     ('medical', 'legal')),
    ("The Genetic Information Nondiscrimination Act prohibits health insurers from using genetic test results as a basis for coverage decisions, which for patients carrying BRCA1 mutations means that prophylactic mastectomy cannot be denied on the grounds that the",
     ('medical', 'legal')),
    ("Involuntary psychiatric commitment proceedings under state mental health laws require clear and convincing evidence that the patient poses an imminent danger, which clinically is assessed through structured risk instruments evaluating suicidal ideation, command hallucinations, and",
     ('medical', 'legal')),
    ("Medicare fraud prosecution under the False Claims Act requires demonstrating that the billing codes submitted for reimbursement did not correspond to the services rendered, which for upcoded cardiac catheterization procedures means proving that the documented stenosis percentage was",
     ('medical', 'legal')),
    ("Class action lawsuits against medical device manufacturers for defective hip implants must establish that the metal-on-metal bearing surface released cobalt and chromium ions into surrounding tissue at concentrations sufficient to cause",
     ('medical', 'legal')),
    ("The Controlled Substances Act schedules drugs based on medical use and abuse potential, and reclassification petitions for compounds like psilocybin require submitting clinical trial evidence demonstrating therapeutic efficacy for treatment-resistant depression with an acceptable",
     ('medical', 'legal')),
    ("Negligence claims against hospitals for healthcare-associated infections require proving that the facility failed to implement evidence-based protocols for central line insertion, including chlorhexidine skin preparation and maximal sterile barriers, which would have prevented catheter-related",
     ('medical', 'legal')),
    ("State medical board disciplinary proceedings for physician impairment require documentation that the practitioner's substance use disorder resulted in clinical performance deficits, which toxicology screening may confirm through detection of benzodiazepine metabolites in concentrations exceeding",
     ('medical', 'legal')),
    ("The Emergency Medical Treatment and Labor Act requires hospital emergency departments to provide a medical screening examination regardless of ability to pay, and failure to diagnose an acute ST-elevation myocardial infarction in a presenting patient constitutes a violation when the electrocardiogram showed",
     ('medical', 'legal')),
    ("Product liability for contaminated blood products requires tracing the donor unit through the blood bank's chain of custody records and demonstrating that nucleic acid testing for hepatitis C virus was not performed despite the availability of approved screening assays that could detect",
     ('medical', 'legal')),
    ("Child abuse reporting statutes impose mandatory disclosure obligations on physicians who observe injuries inconsistent with the reported mechanism, such as retinal hemorrhages in an infant that are characteristic of abusive head trauma and inconsistent with the caregiver's claim of",
     ('medical', 'legal')),
    ("Medical licensure reciprocity agreements between states require verification that the physician's training in a foreign medical school meets equivalency standards, which for graduates of Caribbean institutions means completing USMLE Step examinations with scores demonstrating competency in",
     ('medical', 'legal')),
    ("The Stark Law prohibits physician self-referral for designated health services reimbursed by Medicare, which for radiologists who own imaging centers means they cannot order MRI studies for their own patients unless the arrangement falls within a recognized exception such as",
     ('medical', 'legal')),
    ("Birth injury litigation involving cerebral palsy requires expert testimony establishing that prolonged fetal bradycardia during labor was not promptly addressed by emergency cesarean delivery, and that the resulting hypoxic-ischemic encephalopathy could have been prevented if the obstetrician had interpreted the electronic fetal heart rate tracing showing",
     ('medical', 'legal')),
    ("Vaccine injury compensation through the National Childhood Vaccine Injury Act requires filing a petition with the Court of Federal Claims and demonstrating that symptoms of Guillain-Barré syndrome manifested within the table injury timeframe following administration of",
     ('medical', 'legal')),
    ("Hospice fraud investigations examine whether Medicare-certified agencies enrolled patients who did not meet the terminal prognosis requirement of a life expectancy of six months or less, which for patients with congestive heart failure requires documentation of New York Heart Association Class IV symptoms and an ejection fraction below",
     ('medical', 'legal')),
    ("Advance directive statutes establish the legal framework for patients to specify end-of-life care preferences, and the physician's obligation to follow a do-not-resuscitate order requires verifying the document's validity under state law while assessing whether the patient's current clinical status of irreversible respiratory failure warrants withholding",
     ('medical', 'legal')),

    # ================================================================
    # medical + science (25 probes)
    # ================================================================
    ("The CRISPR-Cas9 system has shown therapeutic potential for treating sickle cell disease by editing the BCL11A enhancer region to reactivate fetal hemoglobin production in hematopoietic stem cells",
     ('medical', 'science')),
    ("Phase III clinical trials of mRNA vaccines demonstrated that the spike protein encoded by the modified nucleoside RNA elicited neutralizing antibody titers that correlated with",
     ('medical', 'science')),
    ("Pharmacogenomics uses genome-wide association studies to identify single nucleotide polymorphisms that predict adverse drug reactions, allowing personalized dosing of medications such as",
     ('medical', 'science')),
    ("Magnetic resonance spectroscopy detects metabolite concentrations in brain tissue by measuring the precession frequencies of hydrogen nuclei in different chemical environments, which in patients with glioblastoma typically shows elevated choline and decreased",
     ('medical', 'science')),
    ("Monoclonal antibody therapeutics are engineered using recombinant DNA technology to target specific epitopes on tumor cells, with chimeric antigen receptor T-cell therapy representing a more personalized approach where the patient's own lymphocytes are modified to express",
     ('medical', 'science')),
    # --- new probes below ---
    ("Positron emission tomography uses fluorodeoxyglucose labeled with fluorine-18 to measure tissue metabolic activity, where the annihilation of the emitted positron with an electron produces two 511 keV gamma rays detected in coincidence by scintillation crystals, allowing clinicians to identify metastatic lesions based on",
     ('medical', 'science')),
    ("Radiation therapy planning uses Monte Carlo simulations of photon transport through heterogeneous tissue to calculate absorbed dose distributions, where the linear-quadratic model predicts that the therapeutic ratio between tumor control and normal tissue complication probability depends on the alpha-beta ratio of",
     ('medical', 'science')),
    ("Antimicrobial resistance mechanisms in methicillin-resistant Staphylococcus aureus involve the mecA gene encoding a modified penicillin-binding protein PBP2a with reduced affinity for beta-lactam antibiotics, which clinically necessitates treatment with vancomycin whose mechanism of action involves binding to the D-Ala-D-Ala terminus of",
     ('medical', 'science')),
    ("Functional magnetic resonance imaging measures blood oxygen level dependent signal changes reflecting neural activity through the paramagnetic properties of deoxyhemoglobin, which in patients with temporal lobe epilepsy reveals lateralized language dominance that determines the surgical approach for",
     ('medical', 'science')),
    ("Pharmacokinetic modeling of monoclonal antibody drugs uses two-compartment models where the distribution phase follows first-order kinetics and clearance occurs through both target-mediated drug disposition and nonspecific catabolism in endothelial cells via the neonatal Fc receptor recycling pathway, which determines the dosing interval for",
     ('medical', 'science')),
    ("Tumor mutational burden measured by whole-exome sequencing correlates with neoantigen load and predicts response to immune checkpoint inhibitor therapy, where patients with mismatch repair deficiency typically exhibit microsatellite instability and generate frameshift mutations that produce",
     ('medical', 'science')),
    ("Diffusion tensor imaging measures the anisotropic diffusion of water molecules along white matter tracts to map neural connectivity, and in patients with traumatic brain injury the fractional anisotropy values in the corpus callosum correlate with the severity of diffuse axonal injury and predict",
     ('medical', 'science')),
    ("Gene therapy for inherited retinal dystrophies uses adeno-associated virus serotype 2 vectors to deliver the RPE65 gene to retinal pigment epithelium cells, where the transgene expression restores the visual cycle by catalyzing the isomerization of all-trans retinyl esters to 11-cis retinal needed for",
     ('medical', 'science')),
    ("Proton beam therapy exploits the Bragg peak phenomenon where charged particles deposit maximum energy at a depth determined by their initial kinetic energy, producing a sharp dose falloff that spares distal normal tissue compared to conventional photon radiation, which is particularly advantageous for treating pediatric brain tumors located near",
     ('medical', 'science')),
    ("Liquid biopsy detection of circulating tumor DNA uses digital droplet PCR or next-generation sequencing to identify cancer-specific mutations in cell-free DNA fragments shed into the bloodstream through apoptosis and necrosis, enabling noninvasive monitoring of minimal residual disease after surgical resection of",
     ('medical', 'science')),
    ("Antisense oligonucleotide therapy for spinal muscular atrophy targets the SMN2 pre-mRNA splicing by blocking the intronic splicing silencer to promote inclusion of exon 7, thereby increasing production of full-length survival motor neuron protein that prevents degeneration of",
     ('medical', 'science')),
    ("Optogenetics has enabled preclinical investigation of deep brain stimulation circuits by expressing channelrhodopsin-2 in specific neuronal populations of the subthalamic nucleus, where blue light activation of these neurons mimics the therapeutic effects observed in Parkinson's disease patients by modulating basal ganglia output through",
     ('medical', 'science')),
    ("Cryo-electron microscopy has resolved the structure of the SARS-CoV-2 spike protein receptor binding domain at near-atomic resolution, revealing the conformational changes required for ACE2 receptor engagement and informing the design of neutralizing antibodies that block viral entry by targeting the",
     ('medical', 'science')),
    ("Transcranial magnetic stimulation delivers brief magnetic pulses that induce electric currents in cortical neurons through electromagnetic induction, and repetitive protocols targeting the dorsolateral prefrontal cortex have demonstrated clinical efficacy for treatment-resistant major depressive disorder by modulating functional connectivity in",
     ('medical', 'science')),
    ("Metabolomics profiling of cerebrospinal fluid using liquid chromatography-mass spectrometry identifies altered concentrations of amyloid-beta 42 and phosphorylated tau protein that serve as biomarkers for Alzheimer's disease, where the ratio of these analytes measured in femtomoles per liter predicts the rate of hippocampal atrophy and",
     ('medical', 'science')),
    ("Induced pluripotent stem cells reprogrammed from patient fibroblasts using Yamanaka factors can be differentiated into cardiomyocytes that recapitulate disease-specific phenotypes, enabling drug screening for hypertrophic cardiomyopathy caused by mutations in the beta-myosin heavy chain gene that alter",
     ('medical', 'science')),
    ("Photodynamic therapy for superficial bladder cancer involves intravesical instillation of a photosensitizer that is preferentially absorbed by neoplastic urothelium, followed by illumination with laser light at the absorption wavelength to generate singlet oxygen through energy transfer from the excited triplet state, causing oxidative damage to",
     ('medical', 'science')),
    ("Genome-wide CRISPR knockout screens in patient-derived tumor organoids identify synthetic lethal gene pairs that can be exploited therapeutically, where loss of BRCA1 function combined with PARP inhibition prevents repair of DNA double-strand breaks through both homologous recombination and base excision repair pathways, leading to",
     ('medical', 'science')),
    ("Mass cytometry using metal-conjugated antibodies enables simultaneous measurement of over 40 surface and intracellular markers on individual immune cells, revealing that patients who respond to anti-PD-1 immunotherapy have a distinct T cell phenotype characterized by high expression of",
     ('medical', 'science')),
    ("Bioprinting of vascularized tissue constructs uses gelatin methacryloyl bioinks deposited by extrusion through coaxial nozzles, where the crosslinking density controlled by UV exposure time determines the elastic modulus that must approximate native tissue stiffness for the printed cardiac patches to support contractile function of",
     ('medical', 'science')),

    # ================================================================
    # legal + code (25 probes)
    # ================================================================
    ("Software patent claims under the Alice framework must demonstrate that the abstract idea is implemented with an inventive concept, which for machine learning algorithms means showing that the specific implementation of gradient descent optimization provides a technical improvement over",
     ('legal', 'code')),
    ("The Digital Millennium Copyright Act safe harbor provisions protect platform operators from liability for user-uploaded content when they implement automated content identification systems using hash-matching algorithms that compare uploaded files against",
     ('legal', 'code')),
    ("Data protection regulations under GDPR require implementing privacy by design, which for database systems means incorporating access control lists, encryption at rest using AES-256, and automated deletion procedures triggered by",
     ('legal', 'code')),
    ("Open source license compliance in corporate software development requires tracking transitive dependencies in package managers, where a single GPL-licensed library in the dependency tree can impose copyleft obligations on",
     ('legal', 'code')),
    ("Algorithmic fairness regulations require that automated decision systems used in lending must demonstrate statistical parity across protected classes, which can be implemented by adding fairness constraints to the loss function during model training such as",
     ('legal', 'code')),
    # --- new probes below ---
    ("The California Consumer Privacy Act grants users the right to request deletion of their personal data, which for distributed systems using eventual consistency means the delete operation must propagate across all replica nodes and backup systems within the compliance window by implementing",
     ('legal', 'code')),
    ("Software escrow agreements for mission-critical enterprise applications require that the deposited source code can be independently compiled and deployed, which means the escrow package must include build configuration files, dependency lock files, and container definitions that reproduce the",
     ('legal', 'code')),
    ("The EU AI Act classifies high-risk artificial intelligence systems that require conformity assessment, which for real-time biometric identification means the system must implement technical documentation including model architecture specifications, training data provenance records, and accuracy metrics disaggregated by",
     ('legal', 'code')),
    ("Section 230 of the Communications Decency Act provides immunity for platforms that moderate content in good faith, but implementing automated content moderation at scale requires natural language processing models that can distinguish protected speech from prohibited material by analyzing",
     ('legal', 'code')),
    ("Anti-circumvention provisions of the DMCA prohibit distributing tools that bypass technological protection measures, which for digital rights management systems means that the encryption key exchange protocol between the media player and license server must implement",
     ('legal', 'code')),
    ("Export control regulations under the Export Administration Act restrict the distribution of cryptographic software with key lengths exceeding specified thresholds, which for open source projects implementing end-to-end encryption means the developers must file a Bureau of Industry and Security notification when the cipher suite includes",
     ('legal', 'code')),
    ("The Sarbanes-Oxley Act requires publicly traded companies to maintain audit trails for financial transactions, which for database management systems means implementing write-ahead logging with tamper-evident hash chains that prevent retroactive modification of",
     ('legal', 'code')),
    ("Accessibility requirements under Section 508 of the Rehabilitation Act mandate that government web applications must be navigable by screen readers, which requires developers to implement proper ARIA attributes, semantic HTML elements, and keyboard focus management in the DOM so that assistive technologies can",
     ('legal', 'code')),
    ("The Computer Fraud and Abuse Act criminalizes unauthorized access to computer systems, and penetration testing engagements must be scoped by written authorization that specifies permitted IP address ranges, testing methodologies, and the types of exploitation techniques allowed such as",
     ('legal', 'code')),
    ("Electronic discovery rules under the Federal Rules of Civil Procedure require parties to preserve and produce electronically stored information in reasonably usable formats, which for organizations using distributed microservices architectures means implementing centralized logging with structured JSON output and immutable storage backends that ensure",
     ('legal', 'code')),
    ("Payment Card Industry Data Security Standard compliance requires that credit card numbers are tokenized before storage, which means the payment processing pipeline must replace the primary account number with a surrogate value using format-preserving encryption algorithms that maintain the Luhn checksum validity of",
     ('legal', 'code')),
    ("The right to algorithmic explanation under GDPR Article 22 requires that automated decisions significantly affecting individuals can be meaningfully explained, which for gradient-boosted tree ensemble models means implementing feature importance extraction using SHAP values that decompose each prediction into additive contributions from",
     ('legal', 'code')),
    ("Trade secret protection for proprietary algorithms under the Defend Trade Secrets Act requires implementing reasonable security measures, which for machine learning model deployment means using techniques like model watermarking, API rate limiting, and differential privacy to prevent adversarial extraction of",
     ('legal', 'code')),
    ("Age verification requirements under the Children's Online Privacy Protection Act mandate that websites collecting data from users under 13 must implement verifiable parental consent mechanisms, which can be achieved through knowledge-based authentication APIs that cross-reference the parent's identity against",
     ('legal', 'code')),
    ("Chain of custody requirements for digital forensic evidence in criminal proceedings mandate that disk images must be cryptographically verified, which means the forensic tool must compute SHA-256 hashes of the acquired image at each transfer point and maintain a log that establishes the integrity of",
     ('legal', 'code')),
    ("The EU Digital Markets Act requires large platform operators to provide interoperability APIs for messaging services, which means implementing end-to-end encrypted message exchange between different platforms using a standardized protocol that handles key distribution, session management, and message format translation between",
     ('legal', 'code')),
    ("Compliance with the Health Insurance Portability and Accountability Act security rule requires implementing technical safeguards in electronic health record systems, including role-based access control with minimum necessary permissions, audit logging of all patient record access events, and automatic session termination after",
     ('legal', 'code')),
    ("The Algorithmic Accountability Act requires impact assessments for automated critical decision systems, which for credit scoring models means documenting the feature engineering pipeline including how variables like zip code are transformed to avoid proxy discrimination through techniques such as",
     ('legal', 'code')),
    ("Software licensing audits for SaaS products require implementing metering systems that accurately track usage against contractual entitlements, which for container-orchestrated deployments means instrumenting the Kubernetes cluster to count active pod instances and API calls per tenant using",
     ('legal', 'code')),
    ("Net neutrality regulations under Title II classification prohibit internet service providers from throttling or prioritizing traffic, which for deep packet inspection systems means the traffic classification engine must operate at line rate using hardware-accelerated pattern matching on packet headers without inspecting application-layer payload to determine whether the traffic is",
     ('legal', 'code')),

    # ================================================================
    # science + code (25 probes)
    # ================================================================
    ("Implementing the Runge-Kutta method for solving ordinary differential equations in numerical simulations of planetary orbits requires careful handling of floating-point precision to maintain energy conservation over",
     ('science', 'code')),
    ("Monte Carlo methods for estimating integrals in high-dimensional spaces use pseudorandom number generators with the Mersenne Twister algorithm providing a period of 2^19937-1 which is sufficient for simulating",
     ('science', 'code')),
    ("Molecular dynamics simulations using the Verlet integration algorithm compute pairwise interatomic forces according to the Lennard-Jones potential, with neighbor list optimizations reducing computational complexity from O(N^2) to",
     ('science', 'code')),
    ("Finite element analysis of stress distributions in materials requires assembling sparse stiffness matrices that can be efficiently solved using conjugate gradient methods with incomplete Cholesky preconditioning for",
     ('science', 'code')),
    ("Training neural network potentials for quantum chemistry calculations involves fitting to density functional theory energy surfaces, where the architecture uses message-passing layers to maintain rotational equivariance of the predicted",
     ('science', 'code')),
    # --- new probes below ---
    ("Fast Fourier transform algorithms reduce the computational complexity of spectral analysis from O(N^2) to O(N log N), enabling real-time processing of radio telescope signals where the Nyquist sampling rate must exceed twice the maximum frequency of the observed electromagnetic",
     ('science', 'code')),
    ("Lattice Boltzmann methods for computational fluid dynamics simulate fluid flow by propagating particle distribution functions on a discrete lattice, where the collision operator uses the Bhatnagar-Gross-Krook approximation with a relaxation parameter that determines the kinematic viscosity of",
     ('science', 'code')),
    ("Adaptive mesh refinement in astrophysical simulations dynamically increases grid resolution near shock fronts and gravitational collapse regions, requiring tree-based data structures that support efficient neighbor queries and load balancing across distributed computing nodes for parallel simulation of",
     ('science', 'code')),
    ("Density functional theory calculations of electronic structure use self-consistent field iteration to solve the Kohn-Sham equations, where the exchange-correlation functional is approximated at the generalized gradient approximation level and the plane-wave basis set requires a kinetic energy cutoff that determines",
     ('science', 'code')),
    ("Particle-in-cell simulations of plasma physics track individual charged particles on a computational grid, where the Boris integrator preserves the symplectic structure of the equations of motion to maintain energy conservation over long time scales when modeling phenomena such as",
     ('science', 'code')),
    ("Markov chain Monte Carlo sampling of posterior distributions in Bayesian inference uses the Metropolis-Hastings algorithm with proposal distributions that must be tuned to achieve optimal acceptance rates near 23.4% in high-dimensional parameter spaces when fitting models to",
     ('science', 'code')),
    ("Smoothed particle hydrodynamics simulations represent fluid as a collection of discrete particles whose properties are interpolated using kernel functions with compact support, and the choice of cubic spline versus Wendland kernel affects the tensile instability that can cause particle clumping in simulations of",
     ('science', 'code')),
    ("Parallel tempering algorithms for protein folding simulations run multiple replicas at different temperatures and exchange configurations according to the Metropolis criterion, where the temperature ladder must be spaced to achieve swap acceptance rates that allow the system to escape local energy minima in the",
     ('science', 'code')),
    ("Spectral methods for solving partial differential equations expand the solution in terms of Chebyshev or Legendre polynomials and compute derivatives in the transform domain with spectral accuracy, but the Gibbs phenomenon near discontinuities requires implementing spectral filtering or artificial viscosity when solving",
     ('science', 'code')),
    ("GPU-accelerated N-body simulations use Barnes-Hut tree algorithms to approximate gravitational forces from distant particle groups as multipole expansions, where the opening angle parameter controls the tradeoff between computational cost and force accuracy for modeling the dynamical evolution of",
     ('science', 'code')),
    ("Wavelet transform analysis of gravitational wave detector data decomposes the signal into time-frequency representations that can distinguish transient astrophysical events from instrumental glitches, where matched filtering with template banks of precomputed waveforms derived from general relativistic binary inspiral models is used to detect",
     ('science', 'code')),
    ("Computational topology algorithms for persistent homology analyze point cloud data by constructing a filtered simplicial complex and tracking the birth and death of topological features across filtration scales, which in materials science is used to characterize the pore structure of",
     ('science', 'code')),
    ("Multigrid methods for solving elliptic partial differential equations accelerate convergence by restricting residuals to coarser grids where low-frequency error components can be efficiently smoothed, then prolongating corrections back to the fine grid using interpolation operators, which is essential for solving the Poisson equation in",
     ('science', 'code')),
    ("Quantum Monte Carlo methods compute ground state energies by stochastically sampling the many-body wave function, where the fixed-node approximation constrains the nodal surface to that of a trial wave function obtained from a preliminary Hartree-Fock calculation to avoid the fermion sign problem when computing the total energy of",
     ('science', 'code')),
    ("Symplectic integrators for Hamiltonian systems preserve the phase space volume exactly at each timestep, which is critical for long-duration solar system simulations where the Wisdom-Holman mapping separates the Hamiltonian into Keplerian and interaction terms and advances each using",
     ('science', 'code')),
    ("Sparse matrix storage formats including compressed sparse row and compressed sparse column are essential for finite element assembly of structural mechanics problems, where the bandwidth of the stiffness matrix can be minimized using the Cuthill-McKee algorithm to reduce fill-in during LU factorization of",
     ('science', 'code')),
    ("Ab initio molecular dynamics simulations compute forces on the fly from electronic structure calculations at each timestep using the Car-Parrinello method, which propagates both nuclear positions and Kohn-Sham orbitals simultaneously by introducing a fictitious electron mass that keeps the electronic subsystem near the Born-Oppenheimer surface during simulation of",
     ('science', 'code')),
    ("Genetic algorithms for optimizing molecular geometries encode atomic coordinates as chromosomes and apply crossover and mutation operators while evaluating fitness through quantum chemical energy calculations at the MP2 or coupled cluster level to locate global minimum energy configurations of",
     ('science', 'code')),
    ("Discontinuous Galerkin methods for solving hyperbolic conservation laws use piecewise polynomial basis functions within each element and communicate through numerical flux functions at element interfaces, where the Riemann solver at each interface determines the upwind direction based on the characteristic speeds of",
     ('science', 'code')),
    ("Coupled atmosphere-ocean general circulation models solve the primitive equations on a rotating sphere using spectral transform methods for horizontal dynamics and finite differences for vertical discretization, where the parameterization of subgrid-scale convection requires a mass flux scheme that determines the rate of latent heat release from condensation in",
     ('science', 'code')),

    # ================================================================
    # medical + code (25 probes)
    # ================================================================
    ("Electronic health record systems implement HL7 FHIR APIs for interoperability, where patient medication lists are represented as MedicationStatement resources that reference standardized drug codes from RxNorm and can be queried using",
     ('medical', 'code')),
    ("Medical image segmentation using U-Net architectures requires training on annotated CT scans where the loss function combines cross-entropy for pixel-wise classification with Dice coefficient to handle class imbalance between tumor and healthy tissue",
     ('medical', 'code')),
    ("Clinical decision support systems use Bayesian networks to compute posterior probabilities of diagnoses given observed symptoms, where the directed acyclic graph structure encodes conditional independence assumptions and inference is performed using",
     ('medical', 'code')),
    ("Implementing a drug interaction checker requires parsing SMILES molecular representations and comparing computed pharmacophore fingerprints against a database of known interactions, flagging combinations where the cytochrome P450 metabolic pathway overlap exceeds",
     ('medical', 'code')),
    ("Wearable biosensor data pipelines process continuous glucose monitor readings at 5-minute intervals, applying Kalman filters to estimate true blood glucose from noisy sensor measurements and triggering insulin pump adjustments when predicted levels exceed",
     ('medical', 'code')),
    # --- new probes below ---
    ("Automated pathology slide analysis uses convolutional neural networks trained on whole slide images at 40x magnification, where the gigapixel input is processed using a patch-based inference pipeline with overlapping tiles and the final heatmap aggregation identifies regions of invasive carcinoma by classifying tissue morphology patterns including",
     ('medical', 'code')),
    ("Real-time arrhythmia detection algorithms in implantable cardiac defibrillators process intracardiac electrograms using digital bandpass filters followed by R-wave peak detection with adaptive thresholds, where the discrimination between ventricular tachycardia and supraventricular tachycardia requires computing the interval stability and morphology correlation using",
     ('medical', 'code')),
    ("Natural language processing of radiology reports uses named entity recognition models trained on clinical text to extract structured findings, where the negation detection module must distinguish between confirmed and ruled-out diagnoses by analyzing dependency parse trees to identify negation cues modifying the mention of",
     ('medical', 'code')),
    ("Robotic surgical systems process stereo camera feeds to generate real-time 3D reconstructions of the operative field, where the image registration pipeline must compensate for tissue deformation during laparoscopic procedures by computing nonrigid transformations using thin-plate spline interpolation of",
     ('medical', 'code')),
    ("Sepsis prediction models deployed in hospital information systems analyze time-series vital signs data using recurrent neural networks with attention mechanisms, where the SOFA score components are computed from laboratory values including platelet count, bilirubin, and creatinine that arrive asynchronously through",
     ('medical', 'code')),
    ("Pharmacy dispensing systems implement barcode-assisted medication verification where the scanned National Drug Code is validated against the electronic prescription using a lookup table that maps NDC numbers to standardized drug identifiers and checks for therapeutic equivalence when generic substitution is",
     ('medical', 'code')),
    ("Radiation treatment planning systems solve the inverse optimization problem of determining beam intensities that maximize tumor dose while satisfying dose constraints on organs at risk, using iterative algorithms that minimize a weighted objective function where the penalty weights for exceeding normal tissue tolerance are",
     ('medical', 'code')),
    ("Telemedicine platforms implementing real-time video consultation must satisfy latency requirements below 150 milliseconds for clinical assessment of neurological signs, where the WebRTC peer connection negotiates codec parameters and the adaptive bitrate algorithm adjusts video quality based on available bandwidth to maintain sufficient resolution for observing",
     ('medical', 'code')),
    ("Clinical trial data management systems implement edit check rules that validate case report form entries against protocol-defined ranges, where the electronic data capture software enforces referential integrity between adverse event records and concomitant medication logs by verifying that the temporal relationship between drug administration and onset of",
     ('medical', 'code')),
    ("Computerized physician order entry systems implement clinical decision support alerts by querying a drug knowledge base for interactions, allergies, and dosing guidelines, where the alert fatigue reduction algorithm uses a Bayesian classifier trained on historical override data to suppress low-severity warnings while escalating notifications for contraindications involving",
     ('medical', 'code')),
    ("Medical device telemetry systems aggregate physiological monitoring data from ICU bedside monitors through a central station server, where the middleware layer converts proprietary serial protocols to standardized IEEE 11073 message formats and routes critical alarms for parameters like mean arterial pressure below the threshold indicating",
     ('medical', 'code')),
    ("Genomic variant calling pipelines process next-generation sequencing data through alignment with BWA-MEM followed by duplicate marking and base quality recalibration before variant detection with GATK HaplotypeCaller, where the quality score QUAL represents the Phred-scaled probability that the alternate allele call at a given position is",
     ('medical', 'code')),
    ("Population health analytics platforms aggregate claims data across payer systems using ETL pipelines that normalize ICD-10 diagnosis codes and CPT procedure codes into standardized clinical groupings, where the risk stratification algorithm assigns patients to cost tiers based on hierarchical condition category scores that predict",
     ('medical', 'code')),
    ("Digital therapeutics for cognitive behavioral therapy deliver interactive treatment modules through mobile applications where the response data from validated psychometric instruments including the PHQ-9 depression screener are scored in real-time and the adaptive algorithm selects the next therapeutic module based on",
     ('medical', 'code')),
    ("Laboratory information management systems track specimen chain of custody from collection through analysis by generating unique accession numbers and recording timestamps at each processing step, where the autoverification rules engine applies delta check algorithms comparing current results against historical patient values to flag specimens where the rate of change in serum potassium exceeds",
     ('medical', 'code')),
    ("Surgical navigation systems fuse preoperative MRI volumes with intraoperative tracking data by computing a rigid body registration between fiducial markers identified in both coordinate systems, where the iterative closest point algorithm minimizes the target registration error to achieve submillimeter accuracy required for resection of",
     ('medical', 'code')),
    ("Emergency department triage algorithms process structured intake data including vital signs, chief complaint, and Emergency Severity Index level through a decision tree classifier that assigns patients to acuity categories, where the real-time dashboard updates bed assignment queues using a priority queue data structure sorted by",
     ('medical', 'code')),
    ("Insulin bolus calculator applications for type 1 diabetes management implement the carbohydrate counting algorithm where the dose is computed from the patient's insulin-to-carbohydrate ratio and correction factor, with the active insulin on board calculation using an exponential decay model whose time constant is determined by the pharmacokinetic profile of",
     ('medical', 'code')),
    ("Federated learning frameworks for multi-site clinical research train diagnostic models across hospital networks without sharing patient data, where each participating site computes local gradient updates on its electronic health record data and the aggregation server combines them using secure multiparty computation protocols that ensure differential privacy with an epsilon budget of",
     ('medical', 'code')),
    ("Automated anesthesia delivery systems use proportional-integral-derivative controllers to maintain target plasma concentrations of propofol based on pharmacokinetic models, where the bispectral index derived from electroencephalogram frequency analysis provides closed-loop feedback and the control algorithm adjusts the infusion rate when the patient's depth of sedation deviates from",
     ('medical', 'code')),

    # ================================================================
    # legal + science (25 probes)
    # ================================================================
    ("Patent prosecution for biotechnology inventions requires demonstrating that gene sequences are markedly different from naturally occurring DNA, following the Supreme Court's ruling in Association for Molecular Pathology v. Myriad Genetics which held that",
     ('legal', 'science')),
    ("Environmental impact assessments under NEPA must quantify the atmospheric dispersion of pollutants using Gaussian plume models that account for wind speed, atmospheric stability class, and stack height to determine whether emissions of particulate matter exceed",
     ('legal', 'science')),
    ("The Daubert standard for admissibility of scientific expert testimony requires courts to evaluate whether the methodology is testable, peer-reviewed, has known error rates, and is generally accepted, which for statistical evidence means assessing whether the confidence interval and p-value of",
     ('legal', 'science')),
    ("Carbon credit trading under cap-and-trade regulations requires verified measurement of greenhouse gas emissions reductions, where direct air capture facilities must demonstrate net removal using lifecycle analysis that accounts for the energy consumed by the amine sorbent regeneration process at",
     ('legal', 'science')),
    ("Regulation of dual-use research of concern in gain-of-function virology requires institutional biosafety committees to evaluate whether the proposed modifications to pathogen transmissibility provide sufficient scientific benefit to justify the enhanced pandemic potential when the research involves",
     ('legal', 'science')),
    # --- new probes below ---
    ("Water quality standards under the Clean Water Act set maximum contaminant levels for toxic pollutants based on dose-response models derived from animal toxicology studies, where the reference dose is calculated by dividing the no-observed-adverse-effect level by uncertainty factors that account for interspecies extrapolation and",
     ('legal', 'science')),
    ("Nuclear regulatory commission licensing of reactor facilities requires probabilistic risk assessment using event tree and fault tree analysis to demonstrate that the core damage frequency does not exceed acceptable thresholds, which for pressurized water reactor designs means quantifying the failure probability of the emergency core cooling system during a loss-of-coolant accident involving",
     ('legal', 'science')),
    ("Forensic DNA evidence presented in criminal trials must account for the population genetics of short tandem repeat allele frequencies, where the random match probability is calculated using the product rule across independent loci with correction factors for population substructure estimated by the theta coefficient of",
     ('legal', 'science')),
    ("The Endangered Species Act requires federal agencies to consult with the Fish and Wildlife Service before authorizing actions that may affect listed species, where the biological opinion analyzes whether the proposed habitat modification will reduce the population viability below the minimum viable population threshold calculated from demographic models incorporating stochastic variation in",
     ('legal', 'science')),
    ("Toxic tort litigation for groundwater contamination requires hydrogeological modeling to trace the contaminant plume from the source to the plaintiff's well, where the advection-dispersion equation governs solute transport through porous media with retardation factors accounting for sorption onto aquifer minerals measured by the distribution coefficient of",
     ('legal', 'science')),
    ("International climate agreements under the Paris framework require nations to report greenhouse gas inventories using IPCC methodologies, where the global warming potential of methane relative to carbon dioxide is calculated over a 100-year time horizon based on the radiative forcing efficiency and atmospheric lifetime of",
     ('legal', 'science')),
    ("Patent claims for pharmaceutical compositions must satisfy the enablement requirement by disclosing sufficient experimental detail for a person skilled in the art to reproduce the invention, which for novel crystalline polymorphs means providing X-ray powder diffraction patterns with characteristic peak positions at two-theta angles that distinguish the claimed form from",
     ('legal', 'science')),
    ("The Montreal Protocol phase-out schedule for ozone-depleting substances assigns different reduction timelines based on the ozone depletion potential of each compound, which is calculated from atmospheric chemistry models that account for the catalytic destruction of stratospheric ozone by chlorine and bromine radicals released during the photolysis of",
     ('legal', 'science')),
    ("Noise ordinances in municipal zoning regulations set maximum permissible sound levels measured in A-weighted decibels at the property boundary, where the acoustic propagation model must account for geometric spreading, atmospheric absorption at frequencies dependent on temperature and humidity, and diffraction over barriers to determine whether industrial operations exceed",
     ('legal', 'science')),
    ("Regulatory approval of genetically modified crops under the Coordinated Framework requires environmental risk assessment including gene flow analysis, where the probability of transgene introgression into wild relatives depends on the outcrossing rate, spatial proximity of compatible species, and the selective advantage conferred by the introduced trait such as",
     ('legal', 'science')),
    ("Occupational exposure limits established by OSHA are derived from epidemiological studies and animal inhalation toxicology data, where the permissible exposure limit for crystalline silica was revised based on quantitative risk assessment showing that cumulative exposure at the previous threshold level produced an excess lifetime risk of silicosis exceeding",
     ('legal', 'science')),
    ("Maritime pollution regulations under MARPOL Annex VI set sulfur content limits for marine fuel oil, and compliance verification requires ships to carry fuel oil bunker delivery notes specifying the sulfur mass fraction determined by X-ray fluorescence spectrometry with a measurement uncertainty that must be subtracted from the test result before comparing against the regulatory limit of",
     ('legal', 'science')),
    ("The Nagoya Protocol on access and benefit sharing requires prior informed consent for collection of biological resources, and material transfer agreements must specify the terms under which extracted secondary metabolites can be screened for pharmaceutical activity using high-throughput bioassays that test compounds against target proteins involved in",
     ('legal', 'science')),
    ("Seismic building codes derive design spectra from probabilistic seismic hazard analysis that integrates over all earthquake sources and magnitudes to determine the spectral acceleration at the fundamental period of the structure with a 2% probability of exceedance in 50 years, corresponding to a return period that depends on the local attenuation relationship between ground motion intensity and",
     ('legal', 'science')),
    ("Pesticide registration under FIFRA requires submission of ecotoxicological data including LC50 values for aquatic organisms determined through standardized bioassays, where the risk quotient is calculated by dividing the estimated environmental concentration derived from spray drift models by the level of concern threshold for",
     ('legal', 'science')),
    ("The Basel Convention controls transboundary movement of hazardous wastes classified by their chemical composition and hazard characteristics, where the leachability of heavy metals from electronic waste is assessed using the Toxicity Characteristic Leaching Procedure that simulates landfill conditions by extracting with acetic acid buffer at pH 4.93 to determine whether the concentration of",
     ('legal', 'science')),
    ("Radiation protection standards established by the Nuclear Regulatory Commission limit public exposure to 1 millisievert per year from licensed activities, where the effective dose is calculated by weighting the absorbed dose in each organ by tissue weighting factors that reflect the relative radiosensitivity and cancer induction probability for different cell types found in",
     ('legal', 'science')),
    ("Regulation of nanotechnology products under TSCA requires manufacturers to submit premanufacture notices with physicochemical characterization data including particle size distribution measured by dynamic light scattering and specific surface area determined by BET nitrogen adsorption, as these properties influence the biological uptake and potential toxicity of",
     ('legal', 'science')),
    ("Mine safety regulations require continuous monitoring of methane concentrations in underground coal mines using catalytic bead sensors calibrated against known gas standards, where the regulatory action level is set below the lower explosive limit of 5% methane in air because turbulent mixing can create local concentration pockets that reach flammable ratios near",
     ('legal', 'science')),
    ("The Chemical Weapons Convention verification regime requires declared facilities to permit on-site inspections by OPCW inspectors, where challenge inspections of suspected production sites involve collection of environmental samples analyzed by gas chromatography-mass spectrometry for trace detection of scheduled precursor chemicals and their hydrolysis products at concentrations as low as",
     ('legal', 'science')),
]
