#!/usr/bin/env python3
"""Extended domain probes for Paper 5 scale validation.

500 probes across 5 domains (100 each) for higher-resolution
coverage-clustering tradeoff measurement.
"""

EXTENDED_DOMAIN_PROBES = {
    'medical': [
        # --- Original 40 from paper3_constellation.py ---
        "The patient presented with acute respiratory distress syndrome requiring",
        "Metformin is commonly prescribed for type 2 diabetes because it",
        "The mechanism of action of selective serotonin reuptake inhibitors involves",
        "Magnetic resonance imaging revealed a lesion in the left temporal lobe",
        "Treatment of hypertension typically begins with lifestyle modifications including",
        "The pathophysiology of Alzheimer's disease involves accumulation of",
        "Cardiac catheterization showed significant stenosis in the left anterior",
        "Immunoglobulin E plays a central role in allergic reactions by",
        "The Glasgow Coma Scale assesses level of consciousness based on",
        "Antibiotic resistance develops through mechanisms including horizontal gene transfer",
        "Pulmonary function tests indicated an obstructive pattern consistent with",
        "The hypothalamic-pituitary-adrenal axis regulates the stress response through",
        "Surgical intervention was indicated due to bowel obstruction caused by",
        "Pharmacokinetics of warfarin are affected by polymorphisms in the CYP2C9",
        "The five-year survival rate for stage III non-small cell lung cancer",
        "Chronic kidney disease is classified into stages based on glomerular filtration",
        "The blood-brain barrier restricts passage of molecules based on their",
        "Electrocardiogram findings consistent with myocardial infarction include ST-segment",
        "Vaccination works by stimulating the adaptive immune system to produce",
        "The differential diagnosis for chest pain includes cardiac, pulmonary, and",
        "Cerebrospinal fluid analysis showed elevated protein and pleocytosis suggesting",
        "Beta-blockers reduce heart rate by antagonizing the effects of catecholamines",
        "The WHO classification of brain tumors is based on histological and",
        "Hemoglobin A1c reflects average blood glucose levels over the preceding",
        "Deep vein thrombosis risk factors include immobilization, surgery, and",
        "The renin-angiotensin-aldosterone system regulates blood pressure through vasoconstriction",
        "Autoimmune diseases result from the immune system attacking self-antigens in",
        "Pain management in palliative care follows the WHO analgesic ladder from",
        "The phases of clinical trials progress from safety assessment in Phase I",
        "Osteoporosis is diagnosed when bone mineral density T-score falls below",
        "Sepsis is defined as life-threatening organ dysfunction caused by a",
        "The cranial nerves include twelve pairs originating from the brainstem",
        "Insulin resistance is a hallmark of metabolic syndrome characterized by",
        "Genetic testing for hereditary breast cancer includes screening for BRCA1",
        "The complement system consists of plasma proteins that enhance innate",
        "Perioperative management of anticoagulation requires balancing bleeding and thrombosis",
        "Rheumatoid arthritis is distinguished from osteoarthritis by the presence of",
        "The stages of wound healing include hemostasis, inflammation, proliferation",
        "Liver cirrhosis complications include portal hypertension, ascites, and hepatic",
        "Neuroplasticity allows the brain to reorganize neural pathways in response to",
        # --- 60 new probes ---
        "Acute pancreatitis is most commonly caused by gallstones and alcohol with elevated serum lipase",
        "The sinoatrial node serves as the primary pacemaker of the heart generating",
        "Parkinson's disease results from dopaminergic neuron degeneration in the substantia nigra",
        "Troponin I levels are elevated in acute myocardial infarction and remain detectable for",
        "The brachial plexus innervates the upper extremity and originates from cervical roots",
        "Diabetic ketoacidosis presents with hyperglycemia, metabolic acidosis, and elevated serum ketones",
        "Helicobacter pylori infection is a major risk factor for peptic ulcer disease and",
        "The glomerular filtration barrier consists of endothelium, basement membrane, and podocyte",
        "Warfarin inhibits vitamin K epoxide reductase thereby reducing synthesis of clotting factors",
        "Cushing syndrome results from chronic glucocorticoid excess causing truncal obesity and",
        "Multiple sclerosis is characterized by demyelination of central nervous system white matter",
        "The Frank-Starling mechanism describes how increased ventricular preload leads to greater stroke",
        "Thyroid function tests reveal elevated TSH and low free T4 in primary hypothyroidism",
        "Pneumothorax is diagnosed by absent breath sounds and hyperresonance on percussion of",
        "The coagulation cascade involves intrinsic and extrinsic pathways converging at factor X",
        "Aortic stenosis produces a crescendo-decrescendo systolic murmur best heard at the right",
        "Crohn's disease differs from ulcerative colitis by transmural inflammation and skip lesions",
        "The Child-Pugh score classifies severity of liver disease using bilirubin, albumin, and",
        "Postoperative atelectasis is prevented by early ambulation, incentive spirometry, and deep",
        "The cerebral arterial circle of Willis provides collateral circulation between the internal",
        "Acute kidney injury is classified by the RIFLE criteria based on creatinine elevation",
        "Phenytoin exhibits zero-order kinetics at therapeutic doses making dosage adjustment particularly",
        "The vagus nerve provides parasympathetic innervation to the heart, lungs, and abdominal",
        "Systemic lupus erythematosus commonly presents with malar rash, joint pain, and antinuclear",
        "Surfactant produced by type II pneumocytes reduces alveolar surface tension preventing",
        "The Wells score estimates pretest probability of pulmonary embolism based on clinical",
        "Graves disease is caused by thyroid-stimulating immunoglobulin binding to the TSH receptor",
        "Myasthenia gravis results from autoantibodies against nicotinic acetylcholine receptors at the",
        "The McGill Pain Questionnaire measures sensory, affective, and evaluative dimensions of",
        "Addison disease presents with hyperpigmentation, hypotension, and electrolyte abnormalities due to",
        "Heparin-induced thrombocytopenia paradoxically increases thrombosis risk through platelet-activating antibodies targeting",
        "The Krebs cycle generates NADH and FADH2 for oxidative phosphorylation in the",
        "Delirium is distinguished from dementia by its acute onset and fluctuating course",
        "Erythropoietin is produced by peritubular interstitial cells of the kidney in response",
        "The TNM staging system classifies tumors by size, lymph node involvement, and",
        "Anaphylaxis requires immediate treatment with intramuscular epinephrine to reverse vasodilation and",
        "Cystic fibrosis results from mutations in the CFTR chloride channel leading to",
        "The apgar score evaluates newborn health at one and five minutes based",
        "Portal hypertension leads to esophageal varices, caput medusae, and splenomegaly as",
        "Methotrexate inhibits dihydrofolate reductase thereby blocking purine synthesis in rapidly dividing",
        "The baroreceptor reflex maintains blood pressure homeostasis by modulating sympathetic and",
        "Sickle cell disease causes vaso-occlusive crises due to polymerization of hemoglobin S",
        "Amyloidosis involves extracellular deposition of misfolded protein fibrils in organs including",
        "The dermatome map indicates that thoracic nerve T10 supplies sensation to the",
        "Clostridium difficile infection typically follows antibiotic use and presents with watery diarrhea",
        "Obstructive sleep apnea is characterized by recurrent upper airway collapse during sleep",
        "The hypothalamus regulates body temperature through shivering thermogenesis and vasodilation of",
        "Pheochromocytoma produces episodic hypertension, headache, and diaphoresis due to catecholamine secretion",
        "Acute appendicitis classically presents with periumbilical pain migrating to the right iliac",
        "The oxyhemoglobin dissociation curve shifts rightward with increased temperature, pCO2, and",
        "Celiac disease is triggered by gluten ingestion causing villous atrophy in the",
        "Lithium toxicity manifests with tremor, ataxia, and renal diabetes insipidus at serum",
        "The lymphatic system returns interstitial fluid to the venous circulation and transports",
        "Guillain-Barre syndrome presents as ascending flaccid paralysis following infection with albuminocytologic",
        "Transfusion reactions range from mild febrile responses to fatal hemolytic reactions caused",
        "The HPA axis suppression from chronic corticosteroid use necessitates gradual tapering to",
        "Endocarditis prophylaxis is recommended for high-risk cardiac conditions before dental procedures involving",
        "The monoamine hypothesis of depression proposes that deficiency of serotonin, norepinephrine, and",
        "Hepatitis B serology showing positive HBsAg and negative anti-HBs indicates active",
        "Cholecystitis presents with right upper quadrant pain, Murphy sign, and fever following",
    ],
    'legal': [
        # --- Original 40 from paper3_constellation.py ---
        "The doctrine of stare decisis requires courts to follow precedent",
        "Under the Fourth Amendment, warrantless searches are presumptively unreasonable",
        "The elements of negligence include duty, breach, causation, and damages",
        "Contract formation requires offer, acceptance, consideration, and mutual assent",
        "The Commerce Clause grants Congress power to regulate interstate commerce",
        "Due process under the Fourteenth Amendment includes both procedural and",
        "The parol evidence rule generally excludes prior oral agreements that contradict",
        "Strict liability applies to abnormally dangerous activities regardless of the",
        "The doctrine of sovereign immunity protects governments from being sued without",
        "Intellectual property rights include patents, trademarks, copyrights, and trade",
        "The burden of proof in criminal cases requires the prosecution to",
        "Fiduciary duty requires acting in the best interest of the beneficiary",
        "The Uniform Commercial Code governs transactions in goods and provides",
        "Res judicata prevents parties from relitigating issues that have already been",
        "The statute of limitations sets the maximum time after an event within",
        "Habeas corpus allows prisoners to challenge the legality of their detention",
        "The exclusionary rule prevents illegally obtained evidence from being admitted",
        "Corporate governance structures include the board of directors, officers, and",
        "Employment at-will doctrine allows either party to terminate the employment",
        "The Clean Air Act establishes national ambient air quality standards for",
        "Antitrust law under the Sherman Act prohibits monopolization and restraint",
        "The right to counsel under the Sixth Amendment applies to all",
        "Tort reform measures include caps on damages and modification of joint",
        "International law sources include treaties, customary law, and general principles",
        "The Equal Protection Clause prohibits states from denying any person within",
        "Bankruptcy proceedings under Chapter 11 allow reorganization of debts while",
        "The Miranda warning must be given before custodial interrogation to protect",
        "Environmental law establishes frameworks for regulating pollution and protecting natural",
        "The doctrine of promissory estoppel enforces promises that induce reasonable",
        "Securities regulation under the SEC requires disclosure of material information",
        "Product liability theories include strict liability, negligence, and breach of",
        "The First Amendment protects freedom of speech from government censorship but",
        "Class action lawsuits allow one party to represent a group with common",
        "Administrative law governs the activities of government agencies including rulemaking",
        "The Takings Clause requires just compensation when private property is taken",
        "Mediation differs from arbitration in that the mediator facilitates negotiation",
        "The legal standard for defamation requires proof of a false statement",
        "Property law distinguishes between real property and personal property based on",
        "The Americans with Disabilities Act prohibits discrimination against individuals with",
        "Maritime law governs activities on navigable waters and includes admiralty",
        # --- 60 new probes ---
        "The Supremacy Clause establishes federal law as the supreme law of the land",
        "Eminent domain allows the government to acquire private property for public use",
        "The Double Jeopardy Clause prevents a defendant from being tried twice for",
        "Qualified immunity shields government officials from civil liability unless they violated clearly",
        "The doctrine of unconscionability allows courts to void contracts that are grossly",
        "Voir dire is the process by which potential jurors are questioned and",
        "The Erie doctrine requires federal courts sitting in diversity to apply state",
        "Comparative negligence reduces a plaintiff's recovery in proportion to their degree of",
        "The Eighth Amendment prohibits cruel and unusual punishment including excessive bail and",
        "Standing requires a plaintiff to demonstrate injury in fact, causation, and",
        "The duty to mitigate damages requires an injured party to take reasonable",
        "Collateral estoppel prevents relitigation of specific issues already determined in a prior",
        "The business judgment rule protects corporate directors from liability for decisions made",
        "Specific performance is an equitable remedy compelling a party to fulfill contractual",
        "The dormant Commerce Clause limits state power to enact laws that burden",
        "Adverse possession allows acquisition of title to land through open and continuous",
        "The felony murder rule imposes liability for deaths occurring during the commission",
        "Forum non conveniens allows courts to dismiss cases when another jurisdiction is",
        "The Chevron doctrine requires courts to defer to agency interpretations of ambiguous",
        "Joint and several liability holds each defendant independently responsible for the full",
        "The Free Exercise Clause protects religious practices from government interference unless a",
        "Whistleblower protections under the False Claims Act incentivize reporting of government fraud",
        "The doctrine of laches bars equitable claims brought after unreasonable delay causing",
        "Piercing the corporate veil allows creditors to reach shareholders' personal assets when",
        "The Confrontation Clause guarantees criminal defendants the right to cross-examine witnesses",
        "Cy pres doctrine allows courts to redirect charitable trust funds to similar",
        "The rule against perpetuities invalidates future interests that may vest beyond the",
        "Contributory negligence in some jurisdictions completely bars recovery if the plaintiff is",
        "The Necessary and Proper Clause grants Congress implied powers to execute its",
        "Indemnification clauses in contracts shift liability from one party to another for",
        "The nondelegation doctrine limits Congress from transferring its legislative power to executive",
        "Temporary restraining orders provide immediate short-term relief before a preliminary injunction hearing",
        "The attractive nuisance doctrine imposes liability on landowners for injuries to trespassing",
        "Compulsory arbitration clauses in employment contracts require disputes to be resolved outside",
        "The privilege against self-incrimination under the Fifth Amendment protects witnesses from being",
        "Tortious interference occurs when a third party intentionally disrupts a contractual relationship",
        "The full faith and credit clause requires states to recognize judicial proceedings",
        "Constructive eviction occurs when a landlord's actions render the premises substantially unsuitable",
        "The political question doctrine prevents courts from adjudicating issues constitutionally committed to",
        "Respondeat superior holds employers vicariously liable for torts committed by employees within",
        "The Establishment Clause prohibits government from establishing or endorsing a particular religion",
        "Exculpatory clauses in contracts attempt to relieve a party from liability for",
        "The statutory rape doctrine imposes strict liability regardless of the defendant's knowledge",
        "Injunctive relief may be permanent or preliminary and requires showing irreparable harm",
        "The penumbra theory derives implied constitutional rights from the specific guarantees of",
        "Negotiable instruments under Article 3 of the UCC must contain an unconditional",
        "The quasi-contract doctrine prevents unjust enrichment when no formal agreement exists between",
        "Extradition treaties govern the transfer of accused persons between sovereign nations for",
        "The abstention doctrine allows federal courts to decline jurisdiction in deference to",
        "Regulatory takings occur when government regulations deprive property owners of economically viable",
        "The substantial evidence standard governs judicial review of administrative agency factual findings",
        "Anticipatory breach allows the non-breaching party to sue before performance is actually",
        "The Tenth Amendment reserves powers not delegated to the federal government to",
        "Good faith and fair dealing is an implied covenant in every contract requiring",
        "The rule of lenity requires ambiguous criminal statutes to be interpreted in",
        "Subrogation allows an insurer who has paid a claim to pursue the",
        "The war powers resolution limits presidential authority to commit armed forces without",
        "Easements by prescription are acquired through continuous adverse use of another's property",
        "The learned intermediary doctrine shields pharmaceutical manufacturers from direct liability to patients",
        "Writ of mandamus compels a government official to perform a ministerial duty",
    ],
    'code': [
        # --- Original 40 from paper3_constellation.py ---
        "def merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr)",
        "class BinarySearchTree:\n    def __init__(self):\n        self.root = None\n    def insert(self",
        "import asyncio\nasync def fetch_data(url):\n    async with aiohttp.ClientSession() as session",
        "def fibonacci(n, memo={}):\n    if n in memo:\n        return memo[n]\n    if n <= 1",
        "SELECT customers.name, orders.total FROM customers INNER JOIN orders ON",
        "const express = require('express');\nconst app = express();\napp.get('/api",
        "def dijkstra(graph, start):\n    distances = {node: float('inf') for node in graph",
        "class LinkedList:\n    class Node:\n        def __init__(self, data):\n            self.data",
        "import torch.nn as nn\nclass TransformerBlock(nn.Module):\n    def __init__(self",
        "def quick_sort(arr, low, high):\n    if low < high:\n        pivot = partition(arr",
        "from flask import Flask, request, jsonify\napp = Flask(__name__)\n@app.route",
        "def depth_first_search(graph, start, visited=None):\n    if visited is None",
        "CREATE TABLE users (\n    id SERIAL PRIMARY KEY,\n    username VARCHAR(50)",
        "class MaxHeap:\n    def __init__(self):\n        self.heap = []\n    def push(self",
        "import numpy as np\ndef gradient_descent(f, grad_f, x0, learning_rate=0.01",
        "async function fetchAPI(endpoint) {\n    try {\n        const response = await fetch",
        "def lru_cache(maxsize=128):\n    def decorator(func):\n        cache = OrderedDict()",
        "class Graph:\n    def __init__(self, directed=False):\n        self.adj = defaultdict",
        "import unittest\nclass TestStringMethods(unittest.TestCase):\n    def test_upper(self",
        "def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left",
        "from dataclasses import dataclass, field\n@dataclass\nclass Config:\n    learning_rate",
        "def knapsack(weights, values, capacity):\n    n = len(weights)\n    dp = [[0",
        "import re\ndef validate_email(email):\n    pattern = r'^[a-zA-Z0-9._%+-]+@",
        "class ThreadPool:\n    def __init__(self, num_workers):\n        self.queue = Queue()",
        "def topological_sort(graph):\n    in_degree = {u: 0 for u in graph}\n    for u",
        "app.use(express.json());\napp.post('/users', async (req, res) => {\n    const",
        "def levenshtein_distance(s1, s2):\n    m, n = len(s1), len(s2)\n    dp = [[0",
        "class RedBlackTree:\n    RED = True\n    BLACK = False\n    def __init__(self",
        "import pandas as pd\ndf = pd.read_csv('data.csv')\ndf_clean = df.dropna(subset",
        "def producer_consumer(buffer_size=10):\n    buffer = queue.Queue(maxsize=buffer_size)",
        "from typing import List, Optional\ndef two_sum(nums: List[int], target: int)",
        "class Singleton:\n    _instance = None\n    def __new__(cls):\n        if cls._instance",
        "import logging\nlogger = logging.getLogger(__name__)\nlogger.setLevel(logging.DEBUG)",
        "def matrix_multiply(A, B):\n    rows_A, cols_A = len(A), len(A[0])\n    rows_B",
        "kubectl apply -f deployment.yaml\napiVersion: apps/v1\nkind: Deployment\nmetadata",
        "class Observable:\n    def __init__(self):\n        self._observers = []\n    def subscribe",
        "def count_inversions(arr):\n    if len(arr) <= 1:\n        return arr, 0\n    mid",
        "from collections import Counter\ndef most_common_words(text, n=10):\n    words",
        "class LRUCache:\n    def __init__(self, capacity):\n        self.capacity = capacity",
        "def a_star(graph, start, goal, heuristic):\n    open_set = [(0, start)]",
        # --- 60 new probes ---
        "def trie_insert(root, word):\n    node = root\n    for char in word:\n        if char not in",
        "SELECT department, AVG(salary) as avg_salary\nFROM employees\nGROUP BY department\nHAVING AVG(salary)",
        "class MinStack:\n    def __init__(self):\n        self.stack = []\n        self.min_stack = []",
        "import itertools\ndef permutations(iterable, r=None):\n    pool = tuple(iterable)\n    n = len(pool)",
        "const WebSocket = require('ws');\nconst wss = new WebSocket.Server({ port: 8080 });\nwss.on('connection",
        "def longest_common_subsequence(s1, s2):\n    m, n = len(s1), len(s2)\n    dp = [[0] * (n + 1)",
        "class AVLTree:\n    def __init__(self, key=None):\n        self.key = key\n        self.left = None",
        "from concurrent.futures import ThreadPoolExecutor\ndef parallel_map(func, items, workers=4):\n    with ThreadPoolExecutor",
        "WITH recursive_cte AS (\n    SELECT id, parent_id, name\n    FROM categories\n    WHERE parent_id IS NULL",
        "def rabin_karp(text, pattern):\n    d = 256\n    q = 101\n    n, m = len(text), len(pattern)",
        "class BloomFilter:\n    def __init__(self, size, hash_count):\n        self.size = size\n        self.bit_array",
        "import socket\ndef create_server(host, port):\n    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)",
        "def bellman_ford(graph, source):\n    dist = {v: float('inf') for v in graph}\n    dist[source] = 0",
        "class CircularBuffer:\n    def __init__(self, capacity):\n        self.buffer = [None] * capacity\n        self.head",
        "from functools import reduce\ndef compose(*functions):\n    return reduce(lambda f, g: lambda x: f(g(x))",
        "app.get('/users/:id', async (req, res) => {\n    const user = await User.findById(req.params.id)",
        "def floyd_warshall(graph):\n    dist = {u: {v: float('inf') for v in graph} for u in graph",
        "class Deque:\n    def __init__(self):\n        self.items = []\n    def add_front(self, item)",
        "import hashlib\ndef compute_checksum(filepath):\n    sha256 = hashlib.sha256()\n    with open(filepath, 'rb')",
        "def huffman_encoding(data):\n    freq = Counter(data)\n    heap = [[f, [c, '']] for c, f in freq",
        "CREATE INDEX idx_orders_date ON orders(order_date);\nEXPLAIN ANALYZE SELECT * FROM orders WHERE order_date",
        "class SegmentTree:\n    def __init__(self, data):\n        self.n = len(data)\n        self.tree = [0]",
        "def kruskal_mst(graph):\n    edges = sorted(graph.edges(), key=lambda e: e[2])\n    parent = {v: v",
        "import multiprocessing\ndef worker(task_queue, result_queue):\n    while True:\n        task = task_queue.get()",
        "const mongoose = require('mongoose');\nconst userSchema = new mongoose.Schema({\n    name: { type: String",
        "def kadane_max_subarray(arr):\n    max_sum = current = arr[0]\n    for num in arr[1:]:\n        current",
        "class UnionFind:\n    def __init__(self, n):\n        self.parent = list(range(n))\n        self.rank = [0]",
        "from sqlalchemy import create_engine, Column, Integer, String\nfrom sqlalchemy.orm import declarative_base\nBase",
        "def reservoir_sampling(stream, k):\n    reservoir = []\n    for i, item in enumerate(stream):\n        if i",
        "class BTreeNode:\n    def __init__(self, leaf=True):\n        self.keys = []\n        self.children = []",
        "import torch\ndef train_step(model, optimizer, batch):\n    model.train()\n    optimizer.zero_grad()",
        "def longest_increasing_subsequence(arr):\n    n = len(arr)\n    dp = [1] * n\n    for i in range(1, n)",
        "const redis = require('redis');\nconst client = redis.createClient();\nclient.on('connect', () => console.log",
        "def sieve_of_eratosthenes(n):\n    is_prime = [True] * (n + 1)\n    is_prime[0] = is_prime[1] = False",
        "class PriorityQueue:\n    def __init__(self):\n        self._queue = []\n        self._index = 0\n    def push",
        "import csv\ndef parse_csv(filepath, delimiter=','):\n    with open(filepath, 'r') as f:\n        reader = csv",
        "def edit_distance(word1, word2):\n    m, n = len(word1), len(word2)\n    dp = [[0] * (n + 1)",
        "class EventEmitter:\n    def __init__(self):\n        self._events = {}\n    def on(self, event, callback)",
        "SELECT p.name, COUNT(o.id) as order_count\nFROM products p LEFT JOIN order_items o\nON p.id = o.product_id",
        "def coin_change(coins, amount):\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for coin",
        "class SkipList:\n    def __init__(self, max_level=16):\n        self.max_level = max_level\n        self.header",
        "import argparse\ndef main():\n    parser = argparse.ArgumentParser(description='Process data')\n    parser.add_argument",
        "def tarjan_scc(graph):\n    index_counter = [0]\n    stack = []\n    lowlink = {}\n    index = {}",
        "class DoublyLinkedList:\n    class Node:\n        def __init__(self, data):\n            self.data = data",
        "from pathlib import Path\ndef walk_directory(root):\n    for path in Path(root).rglob('*'):\n        if path",
        "def word_break(s, word_dict):\n    n = len(s)\n    dp = [False] * (n + 1)\n    dp[0] = True",
        "class ConnectionPool:\n    def __init__(self, max_connections=10):\n        self._pool = []\n        self._semaphore",
        "import json\ndef serialize_graph(graph):\n    return json.dumps({'nodes': list(graph.nodes),\n        'edges': list",
        "def max_flow_ford_fulkerson(graph, source, sink):\n    parent = {}\n    max_flow = 0\n    while bfs",
        "const passport = require('passport');\npassport.use(new LocalStrategy(\n    async (username, password, done) => {",
        "def detect_cycle(graph):\n    visited = set()\n    rec_stack = set()\n    for node in graph:\n        if",
        "class RateLimiter:\n    def __init__(self, max_requests, window_seconds):\n        self.max_requests = max_requests",
        "import sqlite3\ndef init_db(db_path):\n    conn = sqlite3.connect(db_path)\n    cursor = conn.cursor()",
        "def prefix_sum(arr):\n    result = [0] * (len(arr) + 1)\n    for i in range(len(arr)):\n        result",
        "class TrieNode:\n    def __init__(self):\n        self.children = {}\n        self.is_end = False\n    def insert",
        "FROM python:3.11-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r",
        "def matrix_chain_order(dims):\n    n = len(dims) - 1\n    dp = [[0] * n for _ in range(n)",
        "class AsyncQueue:\n    def __init__(self, maxsize=0):\n        self._queue = asyncio.Queue(maxsize=maxsize)",
        "import time\ndef retry_with_backoff(func, max_retries=3, base_delay=1.0):\n    for attempt in range(max_retries)",
        "def sliding_window_max(nums, k):\n    dq = deque()\n    result = []\n    for i, num in enumerate(nums)",
    ],
    'science': [
        # --- Original 40 from paper3_constellation.py ---
        "The standard model of particle physics describes three of the four fundamental",
        "Photosynthesis converts carbon dioxide and water into glucose using light energy",
        "The Heisenberg uncertainty principle states that position and momentum cannot both",
        "Plate tectonics theory explains how Earth's lithosphere is divided into moving",
        "The Drake equation estimates the number of detectable civilizations in the Milky",
        "CRISPR-Cas9 gene editing allows precise modification of DNA sequences by guiding",
        "The second law of thermodynamics states that entropy in an isolated system",
        "Dark matter comprises approximately 27 percent of the universe's mass-energy",
        "The theory of general relativity describes gravity as the curvature of spacetime",
        "Quantum entanglement occurs when particles become correlated such that the state",
        "The Krebs cycle occurs in the mitochondrial matrix and produces electron",
        "Hubble's law describes the relationship between a galaxy's distance and its",
        "Natural selection acts on phenotypic variation within populations leading to",
        "The electromagnetic spectrum ranges from radio waves to gamma rays ordered by",
        "Nuclear fusion in the Sun's core converts hydrogen into helium releasing",
        "The central dogma of molecular biology describes the flow of genetic information",
        "Climate change is driven primarily by anthropogenic emissions of greenhouse gases",
        "Superconductivity occurs when certain materials exhibit zero electrical resistance below a",
        "The periodic table organizes elements by increasing atomic number and recurring",
        "Black holes form when massive stars collapse under their own gravity creating",
        "Enzyme catalysis lowers the activation energy of biochemical reactions through",
        "The double helix structure of DNA was discovered by Watson and Crick",
        "Gravitational waves are ripples in spacetime caused by accelerating massive objects",
        "The ozone layer in the stratosphere absorbs most ultraviolet radiation from",
        "Quantum computing uses qubits that can exist in superposition states unlike",
        "The Big Bang theory describes the origin of the universe from a",
        "Stem cells have the unique ability to differentiate into various specialized",
        "Brownian motion describes the random movement of particles suspended in a",
        "The human genome contains approximately three billion base pairs encoding around",
        "Semiconductor devices work by controlling the flow of electrons through materials",
        "Continental drift was proposed by Alfred Wegener based on the fit of",
        "The speed of light in vacuum is approximately 299,792,458 meters per second",
        "RNA interference is a biological process where RNA molecules inhibit gene expression",
        "The Coriolis effect causes moving objects to be deflected in rotating reference",
        "Photovoltaic cells convert sunlight directly into electricity using semiconductor materials",
        "The mitochondria are often called the powerhouse of the cell because they",
        "Speciation occurs when populations become reproductively isolated leading to divergent",
        "The Chandrasekhar limit is the maximum mass of a stable white dwarf",
        "Epigenetics studies heritable changes in gene expression that do not involve",
        "The Doppler effect describes the change in frequency of a wave relative",
        # --- 60 new probes ---
        "Maxwell's equations unify electricity, magnetism, and optics into a single theoretical framework",
        "The strong nuclear force binds quarks together within protons and neutrons via",
        "Catalytic converters reduce harmful emissions by using platinum group metals to accelerate",
        "The Pauli exclusion principle states that no two fermions can occupy the",
        "Tectonic subduction zones generate deep ocean trenches and volcanic arcs where oceanic",
        "Ribosomes translate messenger RNA into polypeptide chains using transfer RNA as adaptors",
        "The Stefan-Boltzmann law relates the total radiated power of a black body",
        "Neutron stars are composed of degenerate neutron matter with densities exceeding one",
        "Le Chatelier's principle predicts that a system at equilibrium will shift to",
        "The Hardy-Weinberg equilibrium describes allele frequencies in a population that is not",
        "Supernova nucleosynthesis produces elements heavier than iron through rapid neutron capture in",
        "Van der Waals forces include dipole-dipole interactions, London dispersion forces, and",
        "The Schwarzschild radius defines the event horizon of a non-rotating black hole",
        "Chemiosmosis couples electron transport to ATP synthesis across the inner mitochondrial membrane",
        "Fermat's principle states that light follows the path of least time between",
        "The Miller-Urey experiment demonstrated that amino acids could form under prebiotic Earth",
        "Bose-Einstein condensates form when bosons are cooled to near absolute zero and",
        "Isostasy describes the gravitational equilibrium between Earth's lithosphere and asthenosphere causing",
        "The photoelectric effect demonstrated the particle nature of light when electrons were",
        "Endosymbiotic theory proposes that mitochondria and chloroplasts originated as free-living prokaryotes engulfed",
        "The Navier-Stokes equations describe the motion of viscous fluid substances including",
        "Cosmic microwave background radiation is the remnant thermal radiation from the early",
        "Electronegativity increases across a period and decreases down a group in the",
        "The Calvin cycle fixes carbon dioxide into organic molecules using ATP and",
        "Lagrangian mechanics reformulates classical mechanics using the principle of least action and",
        "Radioactive decay follows first-order kinetics with the half-life being the time for",
        "The citric acid cycle produces two molecules of carbon dioxide per acetyl-CoA",
        "Hubble tension refers to the discrepancy between local and early-universe measurements of",
        "Hydrogen bonding between water molecules gives rise to its unusually high specific",
        "The Schrödinger equation describes how the quantum state of a physical system",
        "Convergent evolution produces similar traits in unrelated organisms subjected to comparable selective",
        "The Carnot cycle defines the maximum theoretical efficiency of a heat engine",
        "Redshift of distant galaxies provides evidence for the expansion of the universe",
        "Ionic bonds form between atoms with large electronegativity differences through electron transfer",
        "The Hertzsprung-Russell diagram plots stellar luminosity against surface temperature revealing distinct",
        "Glycolysis breaks down glucose into pyruvate yielding two net ATP molecules in",
        "Helioseismology studies oscillation modes of the Sun to infer its internal structure",
        "Buffer solutions resist changes in pH when small amounts of acid or",
        "The Meissner effect causes superconductors to expel magnetic field lines creating perfect",
        "Horizontal gene transfer allows bacteria to acquire antibiotic resistance genes from other",
        "Kirchhoff's laws relate current and voltage in electrical circuits based on conservation",
        "The Great Oxidation Event approximately 2.4 billion years ago transformed Earth's atmosphere",
        "Chirality in organic chemistry refers to molecules that are non-superimposable mirror images",
        "Pulsars are rapidly rotating neutron stars emitting beams of electromagnetic radiation that",
        "The fluid mosaic model describes cell membranes as lipid bilayers with embedded",
        "Rayleigh scattering explains why the sky appears blue by preferentially scattering shorter",
        "Plate boundaries are classified as divergent, convergent, or transform based on the",
        "Gibbs free energy determines whether a chemical reaction proceeds spontaneously at constant",
        "The anthropic principle observes that the universe's fundamental constants appear fine-tuned for",
        "Meiosis produces four genetically distinct haploid cells through two successive divisions",
        "The Bernoulli principle states that increased fluid velocity results in decreased pressure",
        "Nucleosynthesis in the early universe produced primarily hydrogen and helium during the",
        "Electrochemical cells convert chemical energy to electrical energy through oxidation-reduction reactions at",
        "The holographic principle suggests that all information contained within a volume of",
        "Operons in prokaryotes coordinate gene expression by grouping functionally related genes under",
        "Snell's law relates the angles of incidence and refraction to the refractive",
        "Seafloor spreading at mid-ocean ridges creates new oceanic crust as magma rises",
        "The equipartition theorem assigns equal average kinetic energy to each degree of",
        "Genetic drift causes random changes in allele frequencies that are most pronounced",
        "The Casimir effect demonstrates that quantum vacuum fluctuations produce a measurable attractive",
    ],
    'general': [
        # --- Original 40 from paper3_constellation.py ---
        "The industrial revolution transformed manufacturing processes beginning in Britain during",
        "Democracy as a form of government traces its origins to ancient Athens",
        "The global supply chain connects manufacturers, distributors, and retailers across",
        "Cultural diversity enriches societies by bringing together different perspectives and",
        "Education systems around the world vary significantly in their approach to",
        "The internet has fundamentally changed how people communicate, work, and access",
        "Urban planning involves designing cities to accommodate growing populations while",
        "The history of jazz music reflects the cultural melting pot of",
        "Agricultural practices have evolved from subsistence farming to large-scale industrial",
        "International trade agreements facilitate economic cooperation between nations by reducing",
        "The concept of human rights has evolved through centuries of philosophical",
        "Public transportation systems reduce traffic congestion and carbon emissions in",
        "The Renaissance marked a period of cultural and intellectual rebirth in",
        "Social media platforms have transformed political discourse and public engagement",
        "Climate adaptation strategies help communities prepare for the impacts of",
        "The printing press invented by Gutenberg revolutionized the dissemination of",
        "Modern architecture emphasizes functionality, minimal ornamentation, and the use of",
        "Globalization has increased economic interdependence among nations while raising concerns",
        "The space race between the United States and Soviet Union drove",
        "Sustainable development balances economic growth with environmental protection and social",
        "The evolution of language reflects cultural changes and human migration patterns",
        "Artificial intelligence applications range from virtual assistants to autonomous vehicles",
        "The Olympic Games promote international cooperation and athletic excellence dating back",
        "Food security remains a global challenge affected by climate change and",
        "The civil rights movement in the United States fought for equality",
        "Renewable energy sources including solar, wind, and hydroelectric power are",
        "The United Nations was established in 1945 to maintain international peace",
        "Philosophy of science examines the foundations, methods, and implications of",
        "Migration patterns throughout history have shaped demographic and cultural landscapes",
        "The digital divide refers to the gap between those with and without",
        "Conservation efforts aim to protect biodiversity and preserve natural habitats",
        "The development of antibiotics in the twentieth century dramatically reduced mortality",
        "Economic inequality has been increasing in many developed nations raising questions",
        "The French Revolution fundamentally altered the political landscape of Europe",
        "Cybersecurity threats include malware, phishing, ransomware, and social engineering",
        "The history of mathematics spans from ancient counting systems to modern",
        "Water scarcity affects billions of people worldwide and is projected to",
        "The silk road facilitated trade and cultural exchange between East and",
        "Mental health awareness has increased significantly in recent decades leading to",
        "The theory of evolution by natural selection was independently conceived by",
        # --- 60 new probes ---
        "The Marshall Plan provided economic aid to rebuild Western European economies after",
        "Inflation erodes purchasing power and central banks use interest rate adjustments to",
        "The Panama Canal connects the Atlantic and Pacific Oceans reducing maritime shipping",
        "Urbanization in developing countries creates challenges for infrastructure, housing, and sanitation",
        "The Magna Carta established the principle that everyone including the king is",
        "Cryptocurrency operates on decentralized blockchain technology without requiring a central banking",
        "The Great Wall of China was constructed over centuries to protect northern",
        "Supply and demand curves intersect at equilibrium price where the quantity buyers",
        "The Enlightenment promoted reason, individualism, and skepticism of traditional authority during",
        "Desertification threatens arable land in sub-Saharan Africa due to overgrazing and",
        "The Cold War shaped geopolitical alliances and military strategy from 1947 to",
        "Gross domestic product measures the total value of goods and services produced",
        "The Rosetta Stone enabled scholars to decipher Egyptian hieroglyphs by providing parallel",
        "Automation and robotics are transforming manufacturing industries while raising concerns about",
        "The Byzantine Empire preserved Roman and Greek culture for a thousand years",
        "Microfinance institutions provide small loans to entrepreneurs in developing countries who",
        "The Columbian Exchange transferred plants, animals, and diseases between the Old and",
        "Carbon pricing mechanisms include emissions trading systems and carbon taxes designed to",
        "The Meiji Restoration modernized Japan's political, economic, and military systems in the",
        "Refugee crises are driven by armed conflict, persecution, and environmental disasters",
        "The Harappan civilization developed advanced urban planning and drainage systems in the",
        "Free trade agreements reduce tariffs and promote economic integration between participating nations",
        "The abolitionist movement campaigned against the institution of slavery throughout the eighteenth",
        "Universal basic income proposals aim to provide unconditional cash transfers to all",
        "The Parthenon exemplifies classical Greek architecture with its Doric columns and",
        "Demographic transition describes how birth and death rates change as societies industrialize",
        "The Mongol Empire created the largest contiguous land empire connecting trade routes",
        "Gig economy platforms enable flexible short-term employment but raise questions about",
        "The Reformation challenged the authority of the Catholic Church leading to the",
        "Trade deficits occur when a country's imports exceed its exports affecting",
        "The Suez Canal connects the Mediterranean and Red Seas serving as a",
        "Indigenous knowledge systems preserve ecological understanding accumulated over generations of observation",
        "The Treaty of Westphalia established the modern concept of state sovereignty and",
        "Gentrification revitalizes urban neighborhoods but can displace long-term residents and alter",
        "The Aztec Empire developed sophisticated agriculture including chinampas or floating gardens in",
        "Monetary policy tools include open market operations, reserve requirements, and the discount",
        "The Trans-Siberian Railway connects Moscow to Vladivostok spanning over nine thousand kilometers",
        "Cooperative economics emphasizes collective ownership and democratic decision-making in business organizations",
        "The Bantu migration spread language, agriculture, and iron-working technology across sub-Saharan Africa",
        "Sovereign wealth funds invest national savings from commodity revenues to benefit future",
        "The invention of the telegraph revolutionized long-distance communication in the nineteenth century",
        "Food deserts are areas with limited access to affordable and nutritious food",
        "The Hanseatic League dominated trade in northern Europe during the medieval period",
        "Stagflation combines economic stagnation with high inflation challenging conventional macroeconomic policy",
        "The Age of Exploration expanded European maritime trade and colonization beginning in",
        "Smart city initiatives use technology and data analytics to improve urban services",
        "The Ottoman Empire controlled trade routes between Europe and Asia for six",
        "Behavioral economics studies how psychological factors influence economic decision-making and market",
        "The Berlin Conference of 1884 partitioned Africa among European colonial powers without",
        "Circular economy principles emphasize reducing waste through reuse, recycling, and regenerative",
        "The Green Revolution introduced high-yield crop varieties that dramatically increased food production",
        "Cultural imperialism describes the imposition of dominant culture on less powerful societies",
        "The Phoenicians developed one of the earliest alphabets that influenced Greek and",
        "Quantitative easing involves central banks purchasing financial assets to inject liquidity into",
        "The Rwandan genocide of 1994 demonstrated the devastating consequences of ethnic hatred",
        "Ocean acidification caused by absorbed carbon dioxide threatens marine ecosystems and coral",
        "The Silk Road maritime routes connected China, Southeast Asia, India, and East",
        "Fiscal policy uses government spending and taxation to influence economic conditions and",
        "The Haitian Revolution was the first successful slave revolt leading to the",
        "Biodiversity hotspots contain exceptionally high numbers of endemic species facing significant habitat",
    ],
}
